{% set name = "mesaLib" %}
{% set version = "20.1.4" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.xz
  sha256: 6800271c2be2a0447510eb4e9b67edd9521859a4d565310617c4b359eb6799fe
  patches:
    - 0001_syscall_kcmp.patch

build:
  skip: True  # [win]
  number: {{ build }}

  track_features:
    - mesalib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libxxf86vm-devel') }}
    - {{ cdt('libxshmfence-devel') }}
    - meson
    - mako
    - flex
    - bison

  host:
    - expat
    - zlib
    - libdrm
    - llvmdev<=6.0.1
    - xorg-libx11
    - xorg-libxext
    - xorg-xextproto
    - xorg-glproto
    - xorg-xf86vidmodeproto
    - xorg-libxdamage

  run:
    - xorg-libx11
    - xorg-libxext
    - xorg-xextproto
    - xorg-glproto
    - xorg-xf86vidmodeproto
    - xorg-libxdamage

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  files:
    - glxinfo.c
    - glinfo_common.h
    - glinfo_common.c

  requires:
    - gcc_linux-64
    - pkg-config

  commands:
    - test -f $PREFIX/lib/libGLESv1_CM.so
    - test -f $PREFIX/lib/libGLESv2.so
    - test -f $PREFIX/lib/libOSMesa.so
    - test -f $PREFIX/lib/libGL.so
    - test -f $PREFIX/lib/libglapi.so
    - pkg-config --exists glesv1_cm
    - pkg-config --exists glesv2
    - pkg-config --exists osmesa
    - pkg-config --exists gl
    - x86_64-conda-linux-gnu-gcc `pkg-config --cflags --libs x11 gl` glxinfo.c glinfo_common.c -o glxinfo
    - test -f glxinfo

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - sankhesh
      - danlipsa
      - hmaarrfk
      - muryanto1
      - downiec
      - jasonb5
